### ISSUE TITLE
create 'path' if it doesn't exist

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/geodata#10]
Not a big deal, but the functions with a 'path' argument throw an error if "dir.exists(path) is not TRUE". Unless there's a reason otherwise, it would be useful to add them something like `if(!dir.exists(path)) dir.create(path, recursive = TRUE)`

**Comment by rhijmans** [comment]
The reason I did not do that is that this may happen (at least to me) because of a type. I have now changed it to the middle ground:  `dir.create(path, recursive = FALSE)`

**Comment by AMBarbosa** [comment]
Cool, thanks! This seems to be implemented in most functions, but still missing in `world`, `gadm`, and `elevation_3s`.

**Comment by rhijmans** [comment]
Ay, good catch. My automatic replace did not catch all cases --- as should have been expected. Fixed now.
