### ISSUE TITLE
`world()` returning zero geometries

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/geodata#13]
This was working fine with 'geodata' version 0.4.1, but after updating to 0.4.3, `world()` now returns an object with no geometries or attributes:

`world(resolution = 5, level = 0, path = tempdir())`

The same thing is happening for other values of 'resolution' too. `gadm()` seems to keep working normally, though.

**Comment by rhijmans** [comment]
Hi & thank you --- i believe this works again. I refined the GADM function a bit and that broke this.
