### ISSUE TITLE
GADM update for upcoming 4.1. version:  of Kyrgyzstan borders

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/geodata#14]
Hello,
I know that the new version 4.1. is expected to be released next month (April 2022). I wanted to point out that the Kyrgyzstan border needs an update. Well, in fact it needs it for quite a long time. On the picture below, in yellow is a shapefile from the national dataset, in blue the GADM lvl 1 (but that concerns all levels obviously).  You can see that over the eastern border there are small areas that do not belong to Kyrgyzstan, but China. 
![image](https://user-images.githubusercontent.com/55965799/158394192-0dccdb61-ef73-4419-89cb-ac9aadbe8b49.png)
Here is google maps for a comparison, showing borders following the national dataset. 
![image](https://user-images.githubusercontent.com/55965799/158394565-71ddf77a-018a-4408-8e25-3bccec220bd7.png)

I am just asking to include this in the upcoming update. Thank you!

**Comment by rhijmans** [comment]
This is not a good place for these requests, but it has now been fixed and will soon be avaialble.

**Comment by Rapsodia86** [comment]
Thank you for the update and I apologize for posting in a wrong place.

**Comment by OhmSpectator** [comment]
Sorry for bringing this up, but I'm curious about the right place to ask GADM-related questions. Does GADM have something to do with this project?
