### ISSUE TITLE
WorldClim: .check_cmip6() does not allow for the time period 2081–2100

### ISSUE THREAD

**Issue by basille** [rspatial/geodata#17]
Unless there is something I missed, and a good reason not to include them, the function `cmip6_world()` currently does not allow the download of future climate data from WorldClim for the period 2081–2100. They are however available, as can be seen from the [description page](https://www.worldclim.org/data/cmip6/cmip6climate.html) or from a (randomly selected) [download page](https://geodata.ucdavis.edu/cmip6/10m/CNRM-CM6-1/ssp370/).

It all comes down to modify the `.check_cmip6()` function (line 150 in the [worldclim.R](https://github.com/rspatial/geodata/blob/master/R/worldclim.R) file) with:

```
    stopifnot(time %in% c("2021-2040", "2041-2060", "2061-2080", "2081-2100"))
```

**Comment by basille** [comment]
Closing this issue as it has been fixed in the master branch (not on CRAN yet).

**Comment by rhijmans** [comment]
Thanks, sorry for not responding here earlier.
