### ISSUE TITLE
Citing GBIF data properly

### ISSUE THREAD

**Issue by jhnwllr** [rspatial/geodata#18]
Hello I am writing from **GBIF**. 

I am doing a small outreach to those **R packages** that use GBIF [occurrence search](https://www.gbif.org/developer/occurrence). 

Under the terms of the GBIF data user agreement, users who download data agree to **cite a DOI**. Good citation also rewards data-publishing institutions and individuals by reinforcing the value of sharing open data and demonstrating its impact to their funders.

https://docs.ropensci.org/rgbif/articles/gbif_citations.html
https://www.gbif.org/citation-guidelines

Unfortunately, when using the **occurrence search**, rather than the [occurrence download](https://www.gbif.org/developer/occurrence#download), one does not receive a **citable DOI**. 

Because occurrence search is easier for some users to use, we have created something called **derived datasets**, which allows users to create a **citable DOI** after they have pulled the data from the GBIF public API. 

https://www.gbif.org/derived-dataset

As a package maintainer, it would be appreciated by GBIF, if you could remind users in the documentation or with warning messages to cite the GBIF mediated data properly, perhaps by linking to one of these articles:

https://docs.ropensci.org/rgbif/articles/gbif_citations.html
https://www.gbif.org/citation-guidelines
https://www.gbif.org/derived-dataset

Also important to remind users to keep the **datasetKey** column because this allows for proper attribution to the original data providers.

**Comment by rhijmans** [comment]
Thanks, that is very helpful. I have added this information to the documentation.

**Comment by LuisEnriqueAngelesGonzalez** [comment]
Thank you, I am going to check it out.
