### ISSUE TITLE
`gadm` requires specifying `level`, though it should be 1 by  default

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/geodata#23]
The  "Usage" section of the `gadm()` help file says `level=1` by default, but the function fails if `level` isn't provided:
```
countries <- gadm(country = "Portugal", path = tempdir())

Error in gadm(country = "Portugal", path = tempdir()) : 
  provide a "level=" argument; levels can be 0, 1, or 2 for most countries, and higher for some
```
...whereas for `world()` the "Usage" defaults are working as expected. Cheers

**Comment by rhijmans** [comment]
Thanks! Fixed now.
