### ISSUE TITLE
The package can't connect to server hosted at uc davis

### ISSUE THREAD

**Issue by Rahul-Mathew** [rspatial/geodata#31]
Error in utils::download.file(url = url, destfile = filename, quiet = quiet,  : 
  cannot open URL 'https://geodata.ucdavis.edu/climate/worldclim/2_1/base/wc2.1_5m_elev.zip'
In addition: Warning message:
In utils::download.file(url = url, destfile = filename, quiet = quiet,  :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Error in .downloadDirect(theurl, pzip, unzip = TRUE, ...) : 
  download failed

**Comment by npechl** [comment]
Hi, I have the same problem unfortunately.

**Comment by rhijmans** [comment]
I am assuming that this happens once in a while because of Internet connection issues. Either way, I cannot fix anything if you do not sow what R code you are using that produces this error

**Comment by npechl** [comment]
Sorry for the late answer! 
A couple of days later the problem was fixed (on its own). 
Thank you for your time though.

**Comment by egbendito** [comment]
I am trying to use `geodata::soil_af_isda()` but the function just hangs. For example: 

`geodata::soil_af_isda(var = "clay", path = ".")` just hungs on
`trying URL 'https://geodata.ucdavis.edu/geodata/soil/isda//isda_clay.tot.psa_0-20cm_v0.13_30s.tif'` 

Trying to ping the geodata server with `httr::GET()` but I get the following error message:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [geodata.ucdavis.edu] SSL connection timeout
```

Not sure if this is the same error as this thread or if anyone else is facing this issue.
