### ISSUE TITLE
Feature request: marine variables

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/geodata#37]
Dear Robert,
By now 'geodata' already downloads a great set of environmental variables, but it's still missing the marine environment. When you get a chance for another enhancement, it would be great if 'geodata' could also access the Bio-ORACLE (https://bio-oracle.org/) dataset of present and future marine variables.
Cheers!

**Comment by rhijmans** [comment]
Thanks, great suggestion. There now is a `bio_oracle` function.
