### ISSUE TITLE
elevation_3s() fails with "EXPIRED_CERTIFICATE"

### ISSUE THREAD

**Issue by micha-silver** [rspatial/geodata#39]
Trying to run the `elevation_3s()` fails with:
```
Error in utils::download.file(url = url, destfile = filename, quiet = quiet,  : 
  cannot open URL 'https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_44_06.zip'
download failed
```
When trying to access the download URL directly I get:
```
NET::ERR_CERT_DATE_INVALID
Subject: srtm.csi.cgiar.org
Issuer: R3
Expires on: 2 Nov 2022
```
Is there anyone we can contact to address this problem, and install a new certificate?

**Comment by prayer007** [comment]
I have the same issue ...

**Comment by micha-silver** [comment]
Perhaps send an email to the contact people at Earthdata (https://srtm.csi.cgiar.org/contact-us/):

For Technical Correspondence regarding the SRTM 90m Digital Elevation Data, contact:

Andy Jarvis, Ph.D.
Program Leader – Decision and Policy Analysis
International Centre for Tropical Agriculture (CIAT)
Email: [a.jarvis@cgiar.org](mailto:a.jarvis@cgiar.org)

For site/web related Correspondence regarding the SRTM 90m Digital Elevation Data, contact:

Sadir Mohideen
CSI-CGIAR Chief GeoNetwork Technologist / Senior Web Applications Developmet Specialist
Email: [sadir031@gmail.com](mailto:sadir031@gmail.com)

**Comment by rhijmans** [comment]
Here is a work-around (use additional arguments `method="curl"` and `extra="-k"` to ignore the invalid certificate.  

```
 x <- elevation_3s(4, 48, ".", method="curl", extra="-k")
````

**Comment by prayer007** [comment]
Thank you @rhijmans, thats a workaround, but the best way is it to update the SSL certificate.

**Comment by prayer007** [comment]
And thank you for contacting the CGIAR/CSI folks :)

**Comment by rhijmans** [comment]
This works again.
