### ISSUE TITLE
'population' and 'elevation_global' invalid URLs

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/geodata#4]
Hello,
The functions below are currently returning "no such file or directory" or "invalid 'url' argument" errors. Maybe their files have been renamed or (re)moved in the server?

```
elev <- elevation_global(res = 10, path = tempdir())
pop <- population(year = 2020, res = 10, path = tempdir())
```

**Comment by rhijmans** [comment]
Thank you very much!
