### ISSUE TITLE
The package cannot open connection to UC Davis database website

### ISSUE THREAD

**Issue by QLLZ** [rspatial/geodata#42]
Hi I was trying to run gadm function in geodata package, but since yesterday, it's been returnning connection errors:
```
Error in file(con, "r") : 
  cannot open the connection to 'https://geodata.ucdavis.edu/gadm/gadm4.1.txt'
In addition: Warning message:
In file(con, "r") :
  URL 'https://geodata.ucdavis.edu/gadm/gadm4.1.txt': Timeout of 6000 seconds was reached
trying URL 'https://geodata.ucdavis.edu/gadm/gadm4.1/pck/gadm41_MOZ_1_pk.rds'
Error in utils::download.file(url = url, destfile = filename, quiet = quiet,  : 
  cannot open URL 'https://geodata.ucdavis.edu/gadm/gadm4.1/pck/gadm41_MOZ_1_pk.rds'
download failed
```
Here's my code:
moz <- geodata::gadm(country="MOZ", level=1, path=tempdir())

Not sure if this is because the serve is down or sometihng else?

**Comment by mattwilliamson13** [comment]
+1 to this issue - I'm having the same error for the elevation datasets.
```
elev.us <- elevation_30s(country="USA", path=tempdir())
trying URL 'https://geodata.ucdavis.edu/geodata/elv/USA_elv_msk.zip'
Error in utils::download.file(url = url, destfile = filename, quiet = quiet,  : 
  cannot open URL 'https://geodata.ucdavis.edu/geodata/elv/USA_elv_msk.zip'
In addition: Warning message:
In utils::download.file(url = url, destfile = filename, quiet = quiet,  :
  URL 'https://geodata.ucdavis.edu/geodata/elv/USA_elv_msk.zip': Timeout of 6000 seconds was reached
Error in .downloadDirect(theurl, pzip, unzip = TRUE, ...) : 
  download failed
```

**Comment by Username192837** [comment]
Yes, the website that hosts the WordClim datasets, geodata.ucdavis.edu, is currently down. The website I used to check whether geodata.ucdavis.edu was down or not stated geodata.ucdavis.edu has been down for a week...

Is this down for maintenance? And if so, when will it be back online?

**Comment by rhijmans** [comment]
Very sorry about that. I have lost my backup server for when this happens. The service should be back on no later than April 13.

**Comment by Username192837** [comment]
The server is now operational and I am able to download data. Thank you.

**Comment by QLLZ** [comment]
yes, it's working now, thank you!

**Comment by AMBarbosa** [comment]
Just tried again and the problem seems to be fixed! Cheers

**Comment by AMBarbosa** [comment]
I didn't (consciously) change anything, but the following week, one of my students was getting the same message, though everyone else was OK.

**Comment by joabelb** [comment]
UCDavis is more often offline than online. What's going on over there?

**Comment by CarolinaGarzonL** [comment]
Hi!
The website was working until yesterday. Does anyone know if there’s a backup site or an R package that can be used to access the same data?

**Comment by mulat-amare** [comment]
Hi, I’m having trouble accessing the data server as well. The geodata.ucdavis.edu server isn’t working, and I get a "This site can’t be reached” error when I try to download the files. Do you know if there is any update on when the issue might be resolved? 
Thanks!
