### ISSUE TITLE
Issues with the installation of geodata

### ISSUE THREAD

**Issue by keneldelusca** [rspatial/geodata#43]
Greetings,

I have terra version 1.5-17 installed on a macOS ventura 13.3.1. I want to install the geodata package using the following command:

```
remotes::install_github("rspatial/geodata"), 
```

but it requires version 1.6.41 of terra package. I was unable to update the terra package to the version required by geodata. Any help?

Best regards,
KD

**Comment by rhijmans** [comment]
You are using an ancient version of the terra package and you need to figure out how to update it. You should probably start with installing a more recent version of R. You do not say why you cannot update it, so I cannot provide more help. Either way, this is the geodata repo, not the terra repo. And general "how to" questions like that are probably best asked on stackoverflow.com.
