### ISSUE TITLE
Server down for maintenance?

### ISSUE THREAD

**Issue by Diegoo21** [rspatial/geodata#50]
Hi, we are trying to use the geodata package but when attempting to get worldclim data, the following error appears:

The geodata server is down for maintenance. 
It is expected to be back online on April 13, 2023.

It's past that date, so we're not sure what is going on.

Thanks!

**Comment by krishnakeshav** [comment]
I tried today and it seems to be working alright -
`> geodata::worldclim_country(country = "BRA", var = "tmax", path = tempdir())`

```
trying URL 'https://geodata.ucdavis.edu/climate/worldclim/2_1/tiles/iso/BRA_wc2.1_30s_tmax.tif'
Content type 'image/tiff' length 119444109 bytes (113.9 MB)
==================================================
downloaded 113.9 MB

class       : SpatRaster 
dimensions  : 4740, 5460, 12  (nrow, ncol, nlyr)
resolution  : 0.008333333, 0.008333333  (x, y)
extent      : -74, -28.5, -34, 5.5  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (EPSG:4326) 
source      : BRA_wc2.1_30s_tmax.tif 
names       : BRA_w~max_1, BRA_w~max_2, BRA_w~max_3, BRA_w~max_4, BRA_w~max_5, BRA_w~max_6, ... 
min values  :        -6.4,        -7.2,        -8.3,       -10.3,       -12.8,       -15.6, ... 
max values  :        36.3,        36.3,        36.6,        34.8,        34.0,        34.2, ... 
```

**Comment by Diegoo21** [comment]
Any suggestions on what might be going on from our side? Several of us attempted it again yesterday, even reinstalling the package and still the same message:

> geodata::worldclim_country(country = "BRA", var = "tmax", path = tempdir())
The geodata server is down for maintenance. 
It is expected to be back online on April 13, 2023.
NULL

**Comment by krishnakeshav** [comment]
Can you try pasting this link in your browser -
`https://geodata.ucdavis.edu/climate/worldclim/2_1/tiles/iso/BRA_wc2.1_30s_tmax.tif`
See if you are able to download the tif file directly.

**Comment by Diegoo21** [comment]
The direct download does work.

**Comment by krishnakeshav** [comment]
Just a theory - where are u located? The cloud storage might not be accessible from there.

**Comment by Diegoo21** [comment]
We are at Brigham Young University in Provo, UT.

**Comment by krishnakeshav** [comment]
From the code, it seems to to the direct download. Here are some related issues, I found - #16 and #42 . Do check if any of those helps.

**Comment by gteduarte16** [comment]
> 



> Reinstalled from github and it still doesn't work. I don't see any other suggested solutions on those threads. It seems like it should just eventually get fixed (?)

Following this thread as I have the same issue.

**Comment by dieza** [comment]
Today is june 29, 2026.
And after reinstalling from github. I still got 
"The geodata server is temporary out of service for maintenance. It should be back on 22 June."

**Comment by CarolinaGarzonL** [comment]
Hi!
The website was working until yesterday. Does anyone know if there’s a backup site or an R package that can be used to access the same data?

**Comment by jotavejotave** [comment]
also not working until yesterday for me.

Thing i need ir for tomorrow... im dead if it wont come back
