### ISSUE TITLE
sp_occurrence suggests unsupported * wildcard

### ISSUE THREAD

**Issue by plantarum** [rspatial/geodata#54]
The documentation for sp_occurrence suggests using an * as a wildcard:

https://github.com/rspatial/geodata/blob/6c784653de4b0d8000047e9118d7be21007e3685/man/sp_occurrence.Rd#L40

This doesn't work for me, and after some searching I think the API doesn't support wildcards https://discourse.gbif.org/t/searching-on-catalogue-number/3202

If I try the example from https://rspatial.org/sdm/2_sdm_occdata.html#importing-occurrence-data I get zero results:

```R
library(geodata)
sp_occurrence("solanum", "acaule*", download=FALSE)
```
> [1] 0

Similarly, 

```R
sp_occurrence("solanum", "*", download=FALSE)
```
> [1] 0

Perhaps I don't understand, as I'm not familiar with the GBIF API. But if this should work, I think there's something missing in the documentation, and possibly also the rspatial tutorial, to explain it.

**Comment by rhijmans** [comment]
Thanks. That used to work in some earlier version of the API (perhaps a long time ago). I have removed it from the docs.
