### ISSUE TITLE
geodata archived on CRAN

### ISSUE THREAD

**Issue by achubaty** [rspatial/geodata#71]
> Package ‘geodata’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/geodata).
> 
> Archived on 2024-05-27 as issues were not corrected in time.
>
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2024/2024-05-27_check_results_geodata.html).

the issues appear to be in the donttest tests: https://www.stats.ox.ac.uk/pub/bdr/donttest/geodata.out

**Comment by AMBarbosa** [comment]
@rhijmans maybe replace (this and possibly more instances of) '\donttest' with '\dontrun'? It will break a lot of people's scripts if geodata is no longer on CRAN... Cheers!

**Comment by rhijmans** [comment]
I have been surprised with the removal from CRAN. I addressed the issue, but then they wanted more; perhaps my misunderstanding. Either way, I have re-submitted the package and I hope it will be available again very soon.

**Comment by rhijmans** [comment]
geodata is back on CRAN
