### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by jaunario** [rspatial/geodata#72]
I have a free tier google colab notebook that needs to regularly install geodata. But for some reason, probably a recent push in the repository have caused remotes::install_github("rspatial/geodata") to fail. 

![image](https://github.com/user-attachments/assets/c608d730-d9ed-401e-9304-c8836c7f1a33)

The CRAN package fails to install too.

**Comment by rhijmans** [comment]
Hi Jorrel! 

The install works fine for me (see below, please do not include screen shots). 

It seems that you cannot install "archive" either, so perhaps there is something more general going on. These install problems are often associated with using RStudio. So if you are using RStudio, try the R console instead (in a fresh, empty session. 

I get:
 
```
remotes::install_github("rspatial/geodata")
#Using GitHub PAT from the git credential store.
#Downloading GitHub repo rspatial/geodata@HEAD
#── R CMD build ─────────────────────────────────────────────────────────────────
#   checking for file 'C:\temp\Rtmp4SOATQ\remotes3f0060b73674\rspatial-geodata-6653f49/DESCRIPTION' ...
#✔  checking for file 'C:\temp\Rtmp4SOATQ\remotes3f0060b73674\rspatial-geodata-6653f49/DESCRIPTION'
#─  preparing 'geodata':
#   checking DESCRIPTION meta-information ...
#   checking DESCRIPTION meta-information ... 
#✔  checking DESCRIPTION meta-information
#─  installing the package to process help pages
#─  saving partial Rd database (11.5s)
#─  checking for LF line-endings in source and make files and shell scripts
#─  checking for empty or unneeded directories
#─  building 'geodata_0.6-2.tar.gz'
#* installing *source* package 'geodata' ...
#** using staged installation
#** R
#** inst
#** byte-compile and prepare package for lazy loading
#** help
#*** installing help indices
#** building package indices
#** testing if installed package can be loaded from temporary location
#** testing if installed package can be loaded from final location
#** testing if installed package keeps a record of temporary installation path
#* DONE (geodata)
```

**Comment by jaunario** [comment]
Hi Robert!,

Sorry about the screenshot.

I'm not using RStudio. I developed a tool on Google Colab. It's  essentially an IPython Notebook on a Google Cloud Server. 

I was able to fix the issue by installing terra from Github as well. I was installing terra from CRAN before.

Thanks!
