### ISSUE TITLE
NA data from cmip6_world()

### ISSUE THREAD

**Issue by JoeFDillon** [rspatial/geodata#78]
Kia ora, 

I've tried to download 2081-2100 bioclim data for EC-Earth3-Veg and ACCESS.CM2 using the cmip_world() command. For EC-Earth3-Veg, ssp245 returns a map with all NA values. Likewise, ACCESS.CM2 returned NA values for ssp126. 
Downloading directly from the WorldClim website returns the same. Does anyone know where I can find the actual data?

Cheers,
Joe

**Comment by rhijmans** [comment]
This has now been fixed. Thank you for reporting.
