### ISSUE TITLE
Issues with some CMIP6 files

### ISSUE THREAD

**Issue by geamaro** [rspatial/geodata#79]
Dear friends,

Some files are presenting an error after downloading:

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

After checking, I've found the size of some files seems not to be compatible with others:

https://geodata.ucdavis.edu/cmip6/30s/CMCC-ESM2/ssp585/wc2.1_30s_bioc_CMCC-ESM2_ssp585_2061-2080.tif
https://geodata.ucdavis.edu/cmip6/30s/EC-Earth3-Veg/ssp126/wc2.1_30s_bioc_EC-Earth3-Veg_ssp126_2021-2040.tif

Maybe there are other files with similar problems.

Best wishes.

**Comment by rhijmans** [comment]
This has now been fixed. Thank you.

**Comment by geamaro** [comment]
Thank you!
