### ISSUE TITLE
Broken URLs in soil_af_isda()

### ISSUE THREAD

**Issue by TiagoMonteiroHenriques** [rspatial/geodata#8]
Hello,

Considering function soil_af_isda(), the URLs to download some of the variables appear to be broken, namely: bdr, clay, C.tot, N.tot, sand, silt and texture. All others variables are working as expected.

Thanks for your generosity.

**Comment by rhijmans** [comment]
Thank you very much for reporting this. I am sorry that it took me so long, but I believe this has now been fixed.
