### ISSUE TITLE
Error in In getData from raster

### ISSUE THREAD

**Issue by MeriSoto** [rspatial/geodata#80]
Hi,
I´m trying to import .rds from Mauritania to work on marine data. The package raster has remove the function getData from the old version and this is the error message I get:

> getData('GADM',country="MRT",level=0) 

probando la URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_MRT_0_sp.rds' Error in utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  :    no fue posible abrir la URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_MRT_0_sp.rds' Además: Warning messages: 1: In getData("GADM", country = "MRT", level = 0) :   getData will be removed in a future version of raster . Please use the geodata package instead 2: In utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  :   URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_MRT_0_sp.rds': Timeout of 6000 seconds was reached

apparently in the geodata package there is an analogous funtion that do the same. Could someone help me to import the file "gadm36_MRT_0_sp.rds" in geodata package? Thank you
María

**Comment by rhijmans** [comment]
You can use `geodata::gadm`

**Comment by MeriSoto** [comment]
Thank you!
Regards
María
