### ISSUE TITLE
I can't download the layers of cmip6_tile

### ISSUE THREAD

**Issue by mcohyla** [rspatial/geodata#81]
I can't download all of the Worldclim future layers. I have installed the package geodata with the instruction devtools::install_github("rspatial/geodata", dependencies = TRUE).

[1] "10 - FIO-ESM-2-0 - 245 - 2061-2080 - bioc"
The geodata server is down for maintenance. 
It is expected to be back online by June 25!
download failed

Some layers download well like this: wc2.1_30s_bioc_CNRM-ESM2-1_ssp126_2061-2080_tile-18.

Thanks you for the support.

**Comment by rociobeatrizc** [comment]
Hello, I have the same problem with `worldclim_country("Lux", "tmin", path=tempdir(), res = 0.5, version = "2.1")`

```
The geodata server is down for maintenance. 
It is expected to be back online by June 25!

```
Did you solved it somehow? I tried to download them directly from WorldClim but is not working as well...

**Comment by mcohyla** [comment]
Hello, I don't solve the problem. I am downloading the complete layers with the cmip6_world function.

**Comment by rociobeatrizc** [comment]
Now works for me!

**Comment by mcohyla** [comment]
Hello Robert,
The issue is resolved for worldclim_country. cmip6_tile is not working. Do you have any solution.
Thank you very much,
Martiño

**Comment by rhijmans** [comment]
You are right, sorry about that. I am working to restore it.  That should be done within 24 hrs.

**Comment by rhijmans** [comment]
I think this works again. For example

```
x <- cmip6_tile(5, 50, "CNRM-CM6-1", "585", "2061-2080", var="tmin", path=tempdir())
x
#class       : SpatRaster 
#dimensions  : 3600, 3600, 12  (nrow, ncol, nlyr)
#resolution  : 0.008333333, 0.008333333  (x, y)
#extent      : 0, 30, 30, 60  (xmin, xmax, ymin, ymax)
#coord. ref. : lon/lat WGS 84 (EPSG:4326) 
#source      : wc2.1_30s_tmin_CNRM-CM6-1_ssp585_2061-2080_tile-19.tif 
#names       : wc2.1~in_01, wc2.1~in_02, wc2.1~in_03, wc2.1~in_04, wc2.1~in_05, wc2.1~in_06, ... 
#min values  :       -13.4,       -14.2,       -15.6,       -15.1,       -10.3,        -5.3, ... 
#max values  :        20.6,        14.5,        15.9,        19.8,        25.8,        31.6, ... 
```

**Comment by mcohyla** [comment]
Thank you very much. I have managed to download quite a few layers but some layers cannot be downloaded. I'm going to run all the code to see what they are. Thank you very much for the help.
Look at the server response (note: the first -10 or 10 is longitude (latitude 35)):

[1] "-10 - CNRM-ESM2-1 - 370 - 2061-2080 - bioc"
The geodata server appears to be down.
Hopefully it will be back soon.
download failed
[1] "10 - CNRM-ESM2-1 - 370 - 2061-2080 - bioc"
The geodata server appears to be down.
Hopefully it will be back soon.
download failed

[1] "-10 - EC-Earth3-Veg - 245 - 2041-2060 - bioc"
probando la URL 'https://geodata.ucdavis.edu/cmip6/tiles/EC-Earth3-Veg/ssp245/wc2.1_30s_bioc_EC-Earth3-veg_ssp245_2041-2060_tile-18.tif'
Content type 'image/tiff' length 984994998 bytes (939.4 MB)
downloaded 939.4 MB

[1] "10 - EC-Earth3-Veg - 245 - 2041-2060 - bioc"
probando la URL 'https://geodata.ucdavis.edu/cmip6/tiles/EC-Earth3-Veg/ssp245/wc2.1_30s_bioc_EC-Earth3-Veg_ssp245_2041-2060_tile-19.tif'
Content type 'image/tiff' length 984994990 bytes (939.4 MB)
downloaded 939.4 MB

**Comment by rhijmans** [comment]
To be able to help, you need to show the geodata code you use.  Otherwise I have no way to understand what goes wrong. The first ones may be because a temporarily failing Internet connection.

**Comment by mcohyla** [comment]
The code is very simple:

library(geodata)
path <- "F:/__WorldClim automático IB/"
setwd(path)

model <- c("CNRM-CM6-1", "CNRM-CM6-1-HR", "CNRM-ESM2-1",
           "EC-Earth3-Veg", "EC-Earth3-Veg-LR", "FIO-ESM-2-0", "GFDL-ESM4", "GISS-E2-1-G",
           "GISS-E2-1-H", "HadGEM3-GC31-LL", "INM-CM4-8", "INM-CM5-0", "IPSL-CM6A-LR",
           "MIROC-ES2L", "MIROC6", "MPI-ESM1-2-HR", "MPI-ESM1-2-LR", "MRI-ESM2-0",
           "UKESM1-0-LL")
ssp <- c("245", "370")
time <- c("2041-2060", "2061-2080")
var <- c("bioc")
lon <- c(-10, 10)

for(model.i in model){
  for(ssp.i in ssp){
    for(time.i in time){
      for(var.i in var){
        for(lon.i in lon){
          
          print(paste0(lon.i, " - ", model.i, " - ", ssp.i, " - ", time.i, " - ", var.i))
          cmip6_tile(lon = lon.i, lat = 35, model = model.i, ssp = ssp.i, time = time.i, var = var.i, res = 0.5, path = path)
          
        } 
      }
    }
  }
}

**Comment by rhijmans** [comment]
Thanks, but I cannot run all that. I need to know the specific cases.  Perhaps like this

```
model.i = "EC-Earth3-Veg"
ssp.i  =  "245"
time.i  =  "2041-2060"
var.i  =  "bioc"  
lon.i = 10
geodata::cmip6_tile(lon = lon.i, lat = 35, model = model.i, ssp = ssp.i, time = time.i, var = var.i, res = 0.5, path = path)
```      

And that works for me. You may need to run your code more than once to get all the files.
