### ISSUE TITLE
The geodata server is down for maintenance

### ISSUE THREAD

**Issue by rociobeatrizc** [rspatial/geodata#82]
Hello, this function `> tmin = worldclim_country("Lux", "tmin", path=tempdir(), res = 0.5, version = "2.1")` is not working since yesterday. This is the error I get: 

```
The geodata server is down for maintenance. 
It is expected to be back online by June 25!
```
No solution from other opened or closed Issues here on GitHub worked for me. Does someone have the same problem? Can you suggest an alternative source of monthly climatic data for a country? Thanks!

**Comment by rhijmans** [comment]
This is working again.

**Comment by rociobeatrizc** [comment]
Hello, it seems to be down again. I'll wait!

**Comment by vineetkumar2698-cyber** [comment]
The geodata server is temporary out of service for maintenance. It should be back on 22 June. .. i am using this code...
future <- cmip6_world(
model = "BCC-CSM2-MR",
ssp = "245",
time = "2061-2080",
var = "bio",
res = 2.5,
path = tempdir()
).. somebody can help me please to resolve this.. i urgently need this
