### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by richardtc** [rspatial/geodata#84]
```
> install.packages('geodata', repos='https://rspatial.r-universe.dev')
# Downloading packages -------------------------------------------------------
- Downloading geodata from CRAN ...             OK [269.9 Kb in 3.2s]
tar (child): gzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/tar: Child returned status 2
/bin/tar: Error is not recoverable: exiting now
Error: archive '~/.cache/R/renv/source/repository/geodata/geodata_0.6-2.tar.gz' does not appear to contain a DESCRIPTION file
```

R version: 4.4.1

I get the same error if trying to install from github

Any suggestions are welcome. Thanks

**Comment by rhijmans** [comment]
This works fine for intended platforms. You do not say much about your (e.g. OS), but I see that you are using "renv".  That is a special situation, and you could ask for help with that community (I have no experience with it).

**Comment by richardtc** [comment]
I finally installed as per the above. Couldn't identify the issue, but seems fine now. It was on Ubuntu 22.04 with renv.
