### ISSUE TITLE
Server still down for maintenance 

### ISSUE THREAD

**Issue by atrixkesval** [rspatial/geodata#86]
Hi,
The server is down for maintenance and was expected to be back on the 21st of December, it's now past that time - it is currently the 23rd of December right now where I live. 

 The following line of code isn't working: geodata::worldclim_global(var = 'bio', res = 0.5, download = T, path = 'data'). 

Please tell me when the server will be back, I desperately need it to finish off my coding for my masters thesis which is due in 2 months. Alternatively, I tried to download from the URL as well and it won't work. 

Thanks in advance!

**Comment by Orange-hothot** [comment]
Hi,
I encountered the same issue while running the micro_terra() function.

The geodata server is down for maintenance.It is expected to be back by Dec 21.
Error: unable to find an inherited method for function ‘extract’ for signature ‘x = "NULL", y = "matrix"’

**Comment by Warrenkevin** [comment]
Howdy, Is there an updated still on going with the geodata package? R says it was supposed was supposed to be up by the 21st and it's now the 23rd. If it is still expected to be down for sometime can you update when it will be back on line.  

This is the following error: 

> climate_data <- worldclim_global(var = "bio", res = 2.5, path = tempdir())
The geodata server is down for maintenance.
It is expected to be back by Dec 21.

**Comment by bigrooky** [comment]
> Hi, The server is down for maintenance and was expected to be back on the 21st of December, it's now past that time - it is currently the 23rd of December right now where I live.
> 
> The following line of code isn't working: geodata::worldclim_global(var = 'bio', res = 0.5, download = T, path = 'data').
> 
> Please tell me when the server will be back, I desperately need it to finish off my coding for my masters thesis which is due in 2 months. Alternatively, I tried to download from the URL as well and it won't work.
> 
> Thanks in advance!

Hi,i get the same problem, it seems that this phenomenon has also occurred in the past ,i saw that someone said reinstalling geodata from github would be useful ,but i tried and it didn't work.Have you solved this problem now ? or do we need to wait all the time

**Comment by atrixkesval** [comment]
Hi, 
I also tried reinstalling geodata and that didn't fix the issue for me either. I suspect they'll finish working on it mid January due to everyone being on Christmas/NYE break. 

When I tried googling the issue, it appears that whenever the package is down for maintenance it still seems to be down for everyone 1-2 months after the date listed. This is incredibly anxiety inducing for me....

**Comment by Heed725** [comment]
Same problem, even without coding and trying to fetch data manually  in sites like Diva gis or GADM  you get this error

"Forbidden
You don't have permission to access this resource.

Apache/2.4.52 (Ubuntu) Server at geodata.ucdavis.edu Port 443"

**Comment by nonnohasegawa** [comment]
I hope you guys keep this thread pretty active -- I'm writing my thesis and need these to finish some of my plots!

**Comment by Heed725** [comment]
Hello guys test out your codes and projects ......  i think the server is back online

**Comment by rhijmans** [comment]
Sorry about the unexpectedly long down time.

**Comment by atrixkesval** [comment]
Hi, 
It appears that the server is down for maintenance again. When should we expect this to come back online again as it says "Dec 21"?

**Comment by rhijmans** [comment]
Works for me. Perhaps a problem at your end or a temporary glitch.
